name: Code Formatting

on:
  push:
    paths:
      - '**.c'
      - '**.h'
  pull_request:
    paths:
      - '**.c'
      - '**.h'

jobs:
  format-and-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip3 install c-formatter-42==0.2.1
          pip3 install norminette==3.3.51

      - name: Configure Git
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Format and Lint Code
        run: |
          success=true
          send=false

          # Find C and header files recursively
          files=$(find . -name '*.c' -o -name '*.h')
          
          for file in $files; do
            python3 -m c_formatter_42 < "$file" > "$file.tmp" && mv "$file.tmp" "$file"
            if ! norminette "$file"; then
              success=false
            fi
            
            if [[ $(git status --porcelain "$file") ]]; then
              git add "$file"
              git commit -m "style(format): $file"
              if ! $send; then
                send=true
              fi
            fi
          done

          if $success; then
            echo "Overall Result: Success!"
          else
            echo "Overall Result: Error!"
            exit 1
          fi

          if $send && $success; then
            git remote set-url origin "https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/$GITHUB_REPOSITORY"
            git push origin HEAD:${GITHUB_REF}
          fi
